# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Docker Registry Proxy installation tasks
  tags:
    - setup-all
    - setup-docker-registry-proxy
    - install-all
    - install-docker-registry-proxy
  block:
    - name: Validate Docker Registry Proxy configuration
      when: docker_registry_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Docker Registry Proxy
      when: docker_registry_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Docker Registry Proxy uninstallation tasks
  tags:
    - setup-all
    - setup-docker-registry-proxy
  block:
    - name: Uninstall Docker Registry Proxy
      when: not docker_registry_proxy_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
