# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Docker Registry Proxy systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ docker_registry_proxy_identifier }}.service"
  register: docker_registry_proxy_service_stat

- name: Stop and uninstall Docker Registry Proxy systemd service
  when: docker_registry_proxy_service_stat.stat.exists | bool
  block:
    - name: Ensure Docker Registry Proxy systemd service is stopped
      ansible.builtin.service:
        name: "{{ docker_registry_proxy_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Docker Registry Proxy systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ docker_registry_proxy_identifier }}.service"
        state: absent
