# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Nikita Chernyi
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { "old": "docker_registry_proxy_environment_variables_extension", "new": "docker_registry_proxy_environment_variables_additional_variables" }

- name: Fail if required Docker Registry Proxy settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - docker_registry_proxy_identifier
    - docker_registry_proxy_uid
    - docker_registry_proxy_gid
    - docker_registry_proxy_hostname
    - docker_registry_proxy_path_prefix
    - docker_registry_proxy_container_network

- name: Fail if Docker Registry Proxy hosted at a subpath
  ansible.builtin.fail:
    msg: >-
      Docker Registry Proxy can only be hosted at the base path (`/`), not at a subpath like `{{ docker_registry_proxy_path_prefix }}`).
  when: "docker_registry_proxy_path_prefix != '/'"

- name: Validate Docker Registry Proxy Traefik settings
  when: docker_registry_proxy_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Docker Registry Proxy Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - docker_registry_proxy_container_labels_traefik_hostname
        - docker_registry_proxy_container_labels_traefik_path_prefix
